### PR TITLE
Support Buddy CI/CD

### PR DESCRIPTION
**Pull request by razubuddy**

### CODE REVIEW

**Comment by sztwiorok** [comment]
Hi,

is there any ETA for this?

**Comment by wildan3105** [comment]
hi, following up on this. any ETA to be reviewed? thanks!

**Review by reyhankim — COMMENTED** [review]
excited to see buddy support finally coming to metrik! hopefully we can have this released very soon

**Comment by martinnormark** [comment]
cc @kevinlzw any chance for review and possible release?

**Comment by kevinlzw** [comment]
Done merging this request to main, will do release soon

**Comment by kevinlzw** [comment]
@razubuddy @martinnormark @sztwiorok @wildan3105 Sorry for the long wait. This PR is merged and released.

**Comment by wildan3105** [comment]
> @razubuddy @martinnormark @sztwiorok @wildan3105 Sorry for the long wait. This PR is merged and released.

Hey no worries! I managed to build the image locally using @razubuddy's branch and it succeeded in the first try 😂
So glad that this platform exists! Will definitely contribute in the near soon 🚀

**Comment by kevinlzw** [comment]
Hi @wildan3105 I should thank you all for the great contribution! I have tested the progress bar and it worked greatly.

**Comment by kevinlzw** [comment]
@all-contributors please add @razubuddy  for code

**Pull request merged**
